name: module3_task1
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        run: |
          cd module3_task1
          chmod u+x setup.sh
          ./setup.sh
      - name: Go into correct directory and execute make targets
        run: |
          cd module3_task1
          make build
          make package
          make post
          make clean
          make help
