name: module3_task2
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task2:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        run: |
          cd module3_task2
          chmod u+x setup.sh
          ./setup.sh
      - name: lint markdownfile
        run: |
          cd module3_task2
          make lint
      - name: Go into correct directory and execute make targets
        run: |
          cd module3_task2
          make build
          make run
          make package
          make post
          make clean
          make help

      - name: Archive zip file on success
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v3
        with:
          name: Archive zip file
          path: module3_task2/awesome-website.zip